### Pytorch
- 1) Facebook의 인공지능 연구팀이 개발한 머신러닝, 딥러닝을 위한 라이브러리
- 2) 파이썬 기반의 오픈소스 머신러닝 라이브러리
- 3) 현재 Tensorflow에 비해 사용자는 적으나 간결하고 구현이 빠른 장점으로 인해 점차 사용자가 늘고 있음
- 4) 버전
    - ① 2016년 10월 발표
    - ② 2023년 현재 안정화 버전 2.0.1

https://pytorch.org/get-started/locally/

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

(cmd) nvcc -V 
version 확인 후 맞는 버전 설치

In [1]:
import numpy as np
import torch

li = np.array([[1, 2], [3, 4]])
li

array([[1, 2],
       [3, 4]])

In [2]:
# 넘파이배열을 텐서로 변환
tensor1 = torch.tensor(li)
tensor1

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [3]:
tensor2 = torch.as_tensor(li)
tensor2

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [4]:
tensor3 = torch.from_numpy(li)
tensor3

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [5]:
# 텐서를 넘파이로 변환
tensor1.numpy()

array([[1, 2],
       [3, 4]])

In [6]:
tensor2.numpy()

array([[1, 2],
       [3, 4]])

In [7]:
tensor3.numpy()

array([[1, 2],
       [3, 4]])

In [8]:
torch.manual_seed(0)  # random seed 고정

In [10]:
a = torch.rand(5)   # 0~1 사이 5개난수
b = torch.randn(5)    # 평균0, 표준편차1인 5개 난수
c = torch.randint(10, size=(5,))  # 0~9 사이 5개 난수
a

tensor([0.6341, 0.4901, 0.8964, 0.4556, 0.6323])

In [12]:
b

tensor([ 0.1604, -0.6065, -0.7831,  1.0622, -0.2613])

In [13]:
c

tensor([1, 4, 4, 1, 9])

In [14]:
torch.arange(1,10)   # 1~9

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
torch.ones(2,5)   # 2행 5열, 1로 채움

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [16]:
torch.ones((2,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [17]:
torch.zeros(3,5)   # 3행 5열, 0으로 채움

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [18]:
torch.zeros((3,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
torch.linspace(0,10,5)   # 0~10, 5등분

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [20]:
# tensor의 형상변환
t1 = torch.ones(4,3)
t1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
t1.view(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
t1.view(12)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
t1.view(1,3,4)   # 3차원으로 변환

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])