In [5]:
import cv2
import numpy as np

categories =  ['airplanes', 'Motorbikes' ]
dict_file = 'c:/workspace/Data/plane_bike_dict.npy'
svm_model_file = 'c:/workspace/Data/plane_bike_svm.xml'
imgs = ['c:/workspace/Data/aircraft.jpg','c:/workspace/Data/jetstar.jpg',
        'c:/workspace/Data/motorcycle.jpg', 'c:/workspace/Data/motorbike.jpg']

In [14]:
if imgs is not None:
    for i, path in enumerate(imgs):
        img = cv2.imread(path)
        print(img)
        gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
else:
    print('이미지 로드 안 됨')

[[[179 171 158]
  [179 171 158]
  [179 171 158]
  ...
  [169 161 144]
  [169 161 144]
  [169 161 144]]

 [[179 171 158]
  [179 171 158]
  [179 171 158]
  ...
  [169 161 144]
  [169 161 144]
  [169 161 144]]

 [[179 171 158]
  [179 171 158]
  [179 171 158]
  ...
  [169 161 144]
  [169 161 144]
  [169 161 144]]

 ...

 [[138 132 119]
  [138 132 119]
  [138 132 119]
  ...
  [206 203 198]
  [205 202 197]
  [205 202 197]]

 [[138 132 119]
  [138 132 119]
  [138 132 119]
  ...
  [206 203 198]
  [205 202 197]
  [205 202 197]]

 [[138 132 119]
  [138 132 119]
  [138 132 119]
  ...
  [206 203 198]
  [205 202 197]
  [205 202 197]]]
[[[210 198 194]
  [209 197 193]
  [208 196 192]
  ...
  [188 165 157]
  [188 165 157]
  [188 164 158]]

 [[213 201 197]
  [211 199 195]
  [208 196 192]
  ...
  [188 165 157]
  [188 165 157]
  [188 164 158]]

 [[214 202 198]
  [211 199 195]
  [206 193 191]
  ...
  [187 164 156]
  [187 164 156]
  [188 165 157]]

 ...

 [[186 197 201]
  [186 197 201]
  [186 197 201]
  ..

In [15]:
# 특징 추출기(SIFT) 생성
detector = cv2.xfeatures2d.SIFT_create()
# BOWImgDescriptorExtractor() : 자연어 처리의 Bow(Bag of Words) 알고리즘을 컴퓨터 비전 분야에 활용하여 특징 디스크립터를 추출하는 클래스
bowextractor = cv2.BOWImgDescriptorExtractor(detector, \
                                cv2.BFMatcher(cv2.NORM_L2))
bowextractor.setVocabulary(np.load(dict_file))
svm  = cv2.ml.SVM_load(svm_model_file)

# 이미지 테스트 
for i, path in enumerate(imgs):
    img = cv2.imread(path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # 테스트 이미지에서 BOW 히스토그램 추출 
    hist = bowextractor.compute(gray, detector.detect(gray))
    # SVM 예측 
    ret, result = svm.predict(hist)
    # 결과 표시 
    name = categories[int(result[0][0])]
    txt, base = cv2.getTextSize(name, cv2.FONT_HERSHEY_PLAIN, 2, 3)
    x,y = 10, 50
    cv2.rectangle(img, (x,y-base-txt[1]), (x+txt[0], y+txt[1]), (30,30,30), -1)
    cv2.putText(img, name, (x,y), cv2.FONT_HERSHEY_PLAIN, \
                                 2, (0,255,0), 2, cv2.LINE_AA)
    cv2.imshow(path, img)
cv2.waitKey(0)
cv2.destroyAllWindows()

