In [1]:
import cv2
import numpy as np

img = cv2.imread('c:/workspace/Data/winter.jpg')


In [2]:
K = 16 # cluster 개수(16컬러)

data = img.reshape((-1,3)).astype(np.float32)
# 최대 10회 반복, 1픽셀 이하이면 종료
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
# 클러스터링(K 클러스터 개수, criteria 종료 기준)
ret,label,center=cv2.kmeans(data,K,None,criteria,10,cv2.KMEANS_RANDOM_CENTERS)
center = np.uint8(center)
print('중심좌표:',center)
res = center[label.flatten()]
res = res.reshape((img.shape))
merged = np.hstack((img, res))
cv2.imshow('KMeans Color',merged)
cv2.waitKey(0)
cv2.destroyAllWindows()



중심좌표: [[239 236 230]
 [208 226 244]
 [123 122 124]
 [175 172 170]
 [151 149 150]
 [152 152 207]
 [ 92  91  94]
 [ 59  58  59]
 [197 192 186]
 [228 241 252]
 [190 205 226]
 [ 32  28  88]
 [ 18  16  21]
 [251 250 247]
 [215 210 203]
 [231 226 217]]
