In [2]:
# 라이브러리
import pandas as pd
import numpy as np
from sklearn.preprocessing import minmax_scale


## (sample) 
mtcars 데이터셋(data/mtcars.csv)의 qsec컬럼을 최소최대척도로 변환한 후 0.5보다 큰 값을 가지는 레코드수를 구하시오

In [3]:
# data 불러오기
data = pd.read_csv('data/mtcars.csv')
# print(data['qsec'].head(3))


### 풀이 ①

In [ ]:

# 스케일링
data['qsec'] = minmax_scale(data['qsec'])
# print(data['qsec'].head(3))

# 0.5보다 큰 값 가지는 레코드 수
ans = data['qsec']>0.5
print(sum(ans))

In [ ]:
scaler = MinMaxScaler(feature_range=(0,3)) ## 각 칼럼 데이터 값을 0~3 범위로 변환
scaler.fit(X) ## 각 칼럼 데이터마다 변환할 함수 생성
transformed_X = scaler.transform(X) ## fit에서 만들어진 함수를 실제로 데이터에 적용
print(transformed_X)

### 풀이 ②

In [ ]:
def minmax(data):
    data = (data-min(data)) / (max(data) - min(data))
    return data

data['qsec'] = minmax(data['qsec'])
print(data['qsec'].head(3))

print(len(data[data['qsec']>0.5]))

https://www.kaggle.com/code/stotmyst/tutorial-t1-2-python/edit

## 문제1 
데이터셋(basic1.csv)의 'f5' 컬럼을 기준으로 상위 10개의 데이터를 구하고,

'f5'컬럼 10개 중 최소값으로 데이터를 대체한 후,

'age'컬럼에서 80 이상인 데이터의'f5 컬럼 평균값 구하기

## 문제2
데이터셋(basic1.csv)의 앞에서 순서대로 70% 데이터만 활용해서,

'f1'컬럼 결측치를 중앙값으로 채우기 전후의 표준편차를 구하고

두 표준편차 차이 계산하기

In [ ]:
# 70% 데이터만 사용하기

# 1) iloc
df.shape
df70 = df.iloc[:70]

# 2) np.split
import numpy as np
df70 = np.split(df, [int(.7*len(df))])

# 3) sample
df70 = df.sample(frac = 0.7)
df70 = df.drop(df70.index)
df70

## 문제3

데이터셋(basic1.csv)의 'age'컬럼의 이상치를 더하시오!

단, 평균으로부터 '표준편차*1.5'를 벗어나는 영역을 이상치라고 판단함

In [ ]:
# 이상치 age합
df[(df['age']>max_out)|(df['age']<min_out)]['age'].sum()

# 다르게 작성방법
df.loc[(df['age'] > max)]['age'].sum() + df.loc[(df['age']< min)]['age'].sum()

## T1-1. 이상치를 찾아라

https://www.kaggle.com/code/stotmyst/py-t1-1-iqr-expected-questions/edit

데이터에서 IQR을 활용해 Fare컬럼의 이상치를 찾고, 이상치 데이터의 여성 수를 구하시오

In [ ]:
# IQR 구하기

# 1) describe
q3 = df.Fare.describe()['75%']
q1 = df.Fare.describe()['25%']

# 2) quantile
Q1 = df['Fare'].quantile(.25)
Q3 = df['Fare'].quantile(.75)

# 3) numpy 활용시
Q1 = np.percentile(df['Fare'], 25)
Q3 = np.percentile(df['Fare'], 75)


In [ ]:
# 이상치 데이터 구하기
outlier = iqr*1.5
df_outlier = df[(df.Fare < (q1 - outlier)) | (df.Fare > (q3 + outlier))]

# 이상치 데이터에서 여성 수 구하기, 출력하기 print()
df_outlier.Sex.unique()
df_outlier[df_outlier.Sex == 'female'].shape[0]

## T1-2. 이상치찾기( 소수점 올림, 내림, 버림)
https://www.kaggle.com/code/stotmyst/py-t1-2-expected-questions/edit

주어진 데이터에서 이상치(소수점 나이)를 찾고 

올림, 내림, 버림(절사)했을때 3가지 모두 이상치 'age' 평균을 구한 다음 모두 더하여 출력하시오

In [ ]:
# 소수점 데이터 찾기
import numpy as np

df [ df.age - np.floor(df.age) != 0 ]

In [ ]:
# 소수점 첫째자리에서 반올림
np.round(df.age)  
np.round(df.age, 0)

# 반올림 후 십의자리까지만 표시
np.round(df.age, -1) 

# df.age보다 크거나 같으면서 가장 작은 정수
np.ceil(df.age)   

# df.age보다 작거나 같으면서 가장 큰 정수
np.floor(df.age)

# 소수점 이하 버림
np.trunc(df.agey)

## T1-3. 결측치처리(map) 

https://www.kaggle.com/code/agileteam/py-t1-3-map-expected-questions/notebook

주어진 데이터에서 결측치가 80%이상 되는 컬럼은(변수는) 삭제하고, 80% 미만인 결측치가 있는 컬럼은 'city'별 중앙값으로 값을 대체하고 'f1'컬럼의 평균값을 출력하세요!

In [ ]:
# 80%이상 결측치 컬럼, 삭제
df.drop(df.columns[(df.isnull().sum() / df.shape[0] >= 0.8)][0], axis = 1, inplace = True)

# 결측치가 있는 컬럼을 제거하는 2가지 방법
df.drop(['B', 'C'], axis=1, inplace = True)
df.drop(columns=['B', 'C'], inplace = True)

In [ ]:
# 1) map함수 사용방법1
# city별 중앙값
f1_med = df.groupby(['city']).median()[df.columns[(df.isnull().sum() / df.shape[0] != 0 )][0]]

# dictionary 형태로 바꿔줌(map 함수 사용 위해)
f1_med_dict = f1_med.to_dict()

# f1 결측치를 city별 중앙값으로 대체
df.f1 = df.f1.fillna(df.city.map(f1_med_dict))


In [ ]:
# 2) map함수 사용방법2

k, d, b, s = df.groupby('city')['f1'].median()
df.f1.fillna(df['city'].map({'서울':s,'경기':k,'부산':b,'대구':d}))


In [ ]:
# 결측치 처리여부 확인
df.f1.isnull().sum()

## T1-4. 왜도와 첨도 구하기(로그스케일)

https://www.kaggle.com/code/agileteam/py-t1-4-expected-questions/notebook

주어진 데이터 중 train.csv에서 'SalePrice'컬럼의 왜도와 첨도를 구한 값과, 'SalePrice'컬럼을 스케일링(log1p)로 변환한 이후 왜도와 첨도를 구해 모두 더한 다음 소수점 2째자리까지 출력하시오

#### 왜도
- 음수: 확률밀도함수가 왼쪽으로 긴 꼬리, 오른쪽으로 많이 분포
- 양수: 확률밀도함수가 오른쪽으로 긴 꼬리, 왼쪽으로 많이 분포
- 평균값과 중앙값이 같으면 왜도=0

#### 첨도
- 꼬리가 두꺼운 정도
- 극단적인 편차, 이상치가 많을수록 큰값
- k ~ 3에 가까우면 산포보다 정규분포에 가까움
- k < 3: 정규분포보다 꼬리가 얇은 분포
- k > 3: 정규분포보다 꼬리가 두꺼운 분포

In [ ]:
# 'SalePrice'컬럼 왜도와 첨도계산 
df.SalePrice.skew(), df.SalePrice.kurt()

In [ ]:
# 'SalePrice'컬럼 로그변환
np.log(df.SalePrice)
np.log1p(df.SalePrice)

### 로그변환의 이유
- 로그함수
<br> 0 < x < 1 범위 기울기 가파름. y는 (-무한대,0)  
  x > 1 범위 기울기 작아짐. 넓은 범위의 x를 적은 y의 구간으로 모이게 함
- 데이터를 모았을 때, 밀집되어 있는 부분은 퍼지게, 퍼진 부분은 모아지게 만들 수 있음
<br> ① 클 수를 작게 만들 경우 (제곱단위 차이는 정수, 동일제곱수내 차이는 소숫점자리로 나타남)
<br> ② 복잡한 계산을 간편하게 하려할 경우 (곱셈은 덧셈으로, 나누기는 뺄셈으로바뀜)
<br> ③ 왜도, 첨도를 줄여 정규성을 높이기 위해
<br>

- 단위 SCALE의 문제: 측정 단위가 너무 크거나 작을 때, 상승률로 결과를 논할 때 해석에서 설득력을 가질 수 있음
- 모델 MODEL의 문제: 선형식으로 추정하기 위해 (ex 중력모형, 콥더글라스함수)
- 데이터생성과정 DGP(Data Generating Process): 어떤 변수들이 양싀 실수 내에서만 정의될 경우, 설명변수로 통제할 경우 원칙적으로 바로 OLS 추정을 하면 안 됨. 로그변환을 하면 정의역이 양수, 공역이 모든 실수이기 때문에, 제약식 없이 추정 가능
<br>
참고: https://challenge.tistory.com/46

### np.log() 가 아닌 np.log1p()인 이유
- x가 0의 값을 가지면, 로그변환시 무한대가 됨
- x+1를 해줘서 무한대값이 출력되지 않도록 함: nplog1p()
- 변환 전의 값이 너무 작으면 오류가 생길 수 있으므로, 직접 +1해주기보다 함수사용

## T1-5. 조건에 맞는 데이터 표준편차 구하기

https://www.kaggle.com/code/agileteam/py-t1-5-expected-questions/notebook

주어진 데이터 중 basic1.csv에서 'f4'컬럼 값이 'ENFJ'와 'INFP'인 'f1'의 표준편차 차이를 절대값으로 구하시오

In [ ]:
# 조건에 맞는 데이터 (ENFJ, INFP)
enfj_std = df.loc[df.f4 == 'ENFJ', 'f1'].std()
infp_std = df.loc[df.f4 == 'INFP', 'f1'].std()

# 두 표준편차 차이 절대값 출력
abs(enfj_std - infp_std)
np.abs(enfj_std - infp_std)

## T1-6. 결측치 제거 및 그룹 합계

https://www.kaggle.com/code/agileteam/py-t1-6-expected-questions/notebook

주어진 데이터 중 basic1.csv에서 'f1'컬럼 결측 데이터를 제거하고, 'city'와 'f2'을 기준으로 묶어 합계를 구하고, 'city가 경기이면서 f2가 0'인 조건에 만족하는 f1 값을 구하시오

In [ ]:
# f1컬럼 결측치 제거
df = df[~df.f1.isnull()]

In [ ]:
# 'city'와 'f2'을 기준으로 묶어 합계를 구하고, 
df_sum = df.groupby(['city','f2']).sum()

# 'city가 경기이면서 f2가 0'인 조건에 만족하는 f1 값을 구하시오
df_sum.iloc[0].f1 
df[(df.city == '경기') & (df.f2 == 0)].f1

# 슬라이싱 할 때: 튜플 형태로 할 것
df_sum.loc[('경기',0)].f1

## T1-7. 값 변경 및 2개이상 조건
https://www.kaggle.com/code/agileteam/py-t1-7-2-expected-questions/notebook

'f4'컬럼의 값이 'ESFJ'인 데이터를 'ISFJ'로 대체하고, 'city'가 '경기'이면서 'f4'가 'ISFJ'인 데이터 중 'age'컬럼의 최대값을 출력하시오


In [ ]:
# 값 변경하기
df['f4'] = df['f4'].replace('ESFJ', 'ISFJ')
df.f4.replace('ESFJ','ISFJ', inplace = True)

## T1-8. 누적합, 보간(결측치처리)

https://www.kaggle.com/code/agileteam/py-t1-8-expected-questions/notebook

주어진 데이터 셋에서 'f2' 컬럼이 1인 조건에 해당하는 데이터의 'f1'컬럼 누적합을 계산한다. 이때 발생하는 누적합 결측치는 바로 뒤의 값을 채우고, 누적합의 평균값을 출력한다. (단, 결측치 바로 뒤의 값이 없으면 다음에 나오는 값을 채워넣는다)


In [ ]:
# 조건에 따른 누적합
s = df[df['f2']==1]['f1'].cumsum()
s

In [ ]:
# 바로 뒤값으로 채워넣는 방법
s.fillna(method = 'bfill') 
s.fillna(method = 'backfill')

# 이전값으로 채워넣는 방법
s.fillna(method = 'ffill')
s.fillna(method = 'pad') 

## T1-9. 수치형변수 표준화
https://www.kaggle.com/code/agileteam/py-t1-9-expected-questions/notebook

주어진 데이터에서 'f5'컬럼을 표준화(Standardization (Z-score Normalization))하고 그 중앙값을 구하시오

### Scaling

#### 1. StandardScaler
- 평균=0, 표준편차=1로 조정해서 모든 특성이 같은 크기를 갖게 한다.

#### 2. MinMaxScaler
- 최대값=1, 최소값=0으로 조정, 아웃라이어에 취약

#### 3. RobustScaler
- 중앙값=0, IQR(1분위~3분위값)=1로 조정, 아웃라이어 영향을 최소화하며 정규분포보다 더 넓게 분포

#### 4. MaxAbsScaler
- 0을 기준으로 절대값이 가장 큰 수가 1 또는 -1이 되도록 조정, 양수 데이터로만 구성된 데이터셋에서는 아웃라이어에 민감

#### 아웃라이어 영향 최소화하기 위해서는 1,4 사용
- sklearn에서 제공

### fit_transform() 과 fit(), transform() 차이
- fit()  데이터 학습
- transform() 실제로 학습시킨 것을 적용
<br>

- fit_transform()  한번에 처리. 테스트데이터에서는 쓰면 안 됨
    - ()안에는 dataframe만 들어가야 함
<br>

- test 데이터셋에서는: ss.transform(x_test)


## StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# 1) fit 후 transform
scaler.fit(data)
scaler.transform(data)

# 2) fit과 transform 한꺼번에 진행
scaler.fit_transform(data)

## T-10. 수치형변수 변환, 박스-칼스변환 (출제빈도 낮음)
https://www.kaggle.com/code/agileteam/py-t1-10-expected-questions/notebook

주어진 데이터에서 20세 이상인 데이터를 추출하고 'f1'컬럼을 결측치를 최빈값으로 채운 후, f1 컬럼의 여-존슨과 박스콕스 변환 값을 구하고, 두 값의 차이를 절대값으로 구한다음 모두 더해 소수점 둘째 자리까지 출력(반올림)하시오

In [ ]:
# 조건에 맞는 데이터
df_new = df[df.age>=20]
df_new.f1.mode().values[0]

# 최빈값으로 'f1' 컬럼 결측치 대체
df.f1.fillna(df_new.f1.mode().values[0], inplace = True)

# 'f1'데이터 여-존슨 yeo-johnson 값 구하기 2)
df['f1_yeo2'] = power_transform(df[['f1']],standardize=False) # method 디폴트 값은 여-존슨’yeo-johnson’
df['f1_yeo2'].head()

# 'f1'데이터 박스-콕스 box-cox 값 구하기 2) 
df['f1_box2'] = power_transform(df[['f1']], method='box-cox',standardize=False)
df['f1_box2'].head()

# 두 값의 차이를 절대값으로 구한다음 모두 더해 소수점 둘째 자리까지 출력(반올림)
abs (df.f1_yeo2 - df.f1_box2 ).sum().round(2)

### abs vs np.abs
- np.abs도 내장 함수와 같은 원리로 정수, 실수 및 복소수에 대한 절댓값 연산이 진행되지만, 리스트 혹은 배열 등의 자료에서 내부의 각 원소들에 대하여 통째로 절대값을 취한 결과를 반환받는 것이 가능


In [7]:
import numpy as np
arr = np.array([-1, 2, -3, 4, -5])
np.abs(arr)

array([1, 2, 3, 4, 5])

In [8]:
abs(arr)

array([1, 2, 3, 4, 5])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
np.abs(data2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
abs(data2)

TypeError: bad operand type for abs(): 'list'

## T1-11. min-max 기준 상하위 5%값 

## MinMaxScaler

In [ ]:
# 방법1)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df['f5_1'] = scaler.fit_transform(df[['f5']])

# 방법2)
df['f5_2'] = df['f5'].transform(lambda x: ((x - x.min()) / (x.max() - x.min())))


In [ ]:
# 하위 5%, 상위 5% 값 구하기
df['f5_1'].quantile(0.05)
df['f5_1'].quantile(0.95)


## T1-12. 상위 10개, 하위 10개 차이 

주어진 데이터에서 상위 10개 국가의 접종률 평균과 하위 10개 국가의 접종률 평균을 구하고, 그 차이를 구해보세요 
(단, 100%가 넘는 접종률 제거, 소수 첫째자리까지 출력)


In [ ]:
df_srt = df.groupby('country').max().ratio
df_srt = df_srt[df_srt < 100].sort_values()
bot = df_srt.head(10).mean()
top = df_srt.tail(10).mean()
round(top - bot , 1)

## T1-13. 상관관계 구하기

주어진 데이터에서 상관관계를 구하고, quality와의 상관관계가 가장 큰 값과, 가장 작은 값을 구한 다음 더하시오!
단, quality와 quality 상관관계 제외, 소수점 둘째 자리까지 출력

In [ ]:
df.corr()
df.corr()[:-1]
abs(df.corr()['quality'][:-1]).max()

df.corr()['quality'][:-1][df.corr()['quality'][:-1] == abs(df.corr()['quality'][:-1]).max()].index

## T1-14. 2개 조건에 따른 상위 값

city와 f4를 기준으로 f5의 평균값을 구한 다음, f5를 기준으로 상위 7개 값을 모두 더해 출력하시오 (소수점 둘째자리까지 출력)


In [ ]:
##### OK
df.groupby(['city','f4']).mean().sort_values('f5', ascending = False).head(7).f5.sum().round(2)

## T1-15. 슬라이싱, 조건식
 주어진 데이터 셋에서 age컬럼 상위 20개의 데이터를 구한 다음 
 f1의 결측치를 중앙값으로 채운다.
 그리고 f4가 ISFJ와 f5가 20 이상인 
 f1의 평균값을 출력하시오!


In [ ]:
##### OK
df2 = df.sort_values('age',ascending = False).head(20)
df2.f1.fillna(df2.f1.median(), inplace = True)
df2[(df2.f4 == 'ISFJ') & (df2.f5 >= 20)].f1.mean()

## T1-16. 분산
 주어진 데이터 셋에서 f2가 0값인 데이터를 age를 기준으로 오름차순 정렬하고
 앞에서 부터 20개의 데이터를 추출한 후 
 f1 결측치(최소값)를 채우기 전과 후의 분산 차이를 계산하시오 (소수점 둘째 자리까지)


In [ ]:
##### OK
df1 = df[df.f2 == 0].sort_values('age').head(20)
var1 = df1.f1.var()
df2 = df1
df2.f1.fillna(df2.f1.min(), inplace = True)
var2 = df2.f1.var()
round(var1 - var2, 2)

### 분산, 표준편차
#### ddof : Delta Degrees of Freedom 감소된 자유도
- numpy as np
    - 모표준편차 ddof=0 가 디폴트
    - df.f1.values.var()
    - df.f1.var(ddof = 0)
    - np.var(df.f1)
- pandas as pd
    - 표본표준편차 ddof=1 가 디폴트  (n-1)로 나눔
    - df.f1.var()
    - df.f1.var(ddof = 1)
    - np.var(df.f1, ddof = 1)

## T1-17. 시계열1 

2022년 5월 sales의 중앙값


In [ ]:
##### OK
import datetime as dt
df.Date = pd.to_datetime(df.Date)
df.Date.unique()
df[(df.Date.dt.year == 2022) & (df.Date.dt.month == 5)].Sales.median()

## T1-18. 시계열2

주어진 데이터에서 2022년 5월 주말과 평일의 sales컬럼 평균값 차이를 구하라
소수점 둘째자리까지 출력, 반올림

In [ ]:
new = df[(df.Date.dt.year == 2022) & (df.Date.dt.month == 5)]
new['Day'] = new.Date.dt.weekday.isin([5,6])
round(abs(new[new.Day == True].Sales.mean() - new[new.Day == False].Sales.mean()),2)

### 요일
- df.dt.dayofweek
- df.dt.weekday

## T1-19. 시계열3

주어진 데이터에서 2022년 월별 Sales 합계 중 가장 큰 금액과
2023년 월별 Sales 합계 중 가장 큰 금액의 차이를 절대값으로 구하시오.
단 Events컬럼이 '1'인경우 80%의 Salse값만 반영함
(최종값은 소수점 반올림 후 정수 출력)

In [ ]:
# 조건에 맞는 컬럼 만들기

# 방법1)
def eve(x):
    if x.Events == 1:
        x['new_sales'] = x.Sales * 0.8
    else:
        x['new_sales'] = x.Sales
    return x

df = df.apply(lambda x: eve(x), axis = 1)

# 방법2)
df['newSales'] = df.Sales.apply(lambda x: x*0.8 if (df[df.Sales == x].Events.values) == 1 else x)

# 차이, 절대값 소수점 반올림 후 정수출력
int(round(abs(a - b),0))

### apply(lambda) 함수
- 한 개의 레코드(로우)별로 체크해서 변환하겠다는 의미임
<br>
- pandas DataFrame은 기본적으로 레코드 단위가 아닌, 컬럼 단위로 일괄 변환을 선호함
- 레코드 단위 변환이 필요할 경우에, apply(lambda)를 사용
    - df.Sales.apply(lambda x: get_category(x)): 1건의 Sales값이 get_category(x)의 x로 입력됨
    - df.Sales.apply(lambda x: df.Sales : 오류가 나는 건 당연함

## T1-20. 데이터 병합

basic1 데이터와 basic3 데이터를 'f4'값을 기준으로 병합하고,
병합한 데이터에서 r2결측치를 제거한다음, 앞에서 부터 20개 데이터를 선택하고 'f2'컬럼 합을 구하시오

In [ ]:
# merge
b2 = b1.merge(b3, on='f4')
df = pd.merge(left = b1 , right = b3, how = "left", on = "f4")

# 결측치 제거
b2.dropna(subset=['r2'])

## T1-21. 구간분할

basic1 데이터 중 'age'컬럼 이상치를 제거하고, 동일한 개수로 나이 순으로 3그룹으로 나눈 뒤 각 그룹의 중앙값을 더하시오

In [ ]:
# 구간 분할
df['range'] = pd.qcut(df['age'], q=3, labels=['group1','group2','group3'])

### 구간나누기
- 같은 길이로 구간 나누기: pd.cut 
- 같은 갯수로 구간 나누기: pd.qcut

#### 값이 float일 때

In [3]:
np.random.seed(122)

In [7]:
normal = np.random.normal(size = 10000)
normal

array([ 0.48468014, -0.82216117, -0.33674179, ..., -0.11182173,
       -0.53074846, -0.41525932])

In [6]:
bins = pd.cut(normal, 5)
bins

[(-0.701, 0.779], (-2.18, -0.701], (-0.701, 0.779], (-2.18, -0.701], (0.779, 2.258], ..., (-2.18, -0.701], (-0.701, 0.779], (-0.701, 0.779], (-0.701, 0.779], (-0.701, 0.779]]
Length: 10000
Categories (5, interval[float64, right]): [(-3.667, -2.18] < (-2.18, -0.701] < (-0.701, 0.779] < (0.779, 2.258] < (2.258, 3.738]]

In [8]:
bins.categories

IntervalIndex([(-3.667, -2.18], (-2.18, -0.701], (-0.701, 0.779], (0.779, 2.258], (2.258, 3.738]], dtype='interval[float64, right]')

In [9]:
bins.describe()

counts   freqs
categories                     
(-3.667, -2.18]     161  0.0161
(-2.18, -0.701]    2214  0.2214
(-0.701, 0.779]    5464  0.5464
(0.779, 2.258]     2054  0.2054
(2.258, 3.738]      107  0.0107

In [10]:
## 직접 나눠보기
mn = normal.min()
mx = normal.max()
delta = mx - mn
size = delta / 5
etr = delta * 0.001
intval = np.arange(mn, mx+etr, size)
intval

array([-3.65918563, -2.17984729, -0.70050894,  0.7788294 ,  2.25816774,
        3.73750609])

In [11]:
intval[0] -= delta*0.001
intval

array([-3.66658232, -2.17984729, -0.70050894,  0.7788294 ,  2.25816774,
        3.73750609])

#### 값이 int일 때

In [12]:
ages = np.random.randint(6,45,50)
ages

array([27, 32, 42, 33, 37,  8, 34, 36, 42, 41, 14, 23, 12, 19, 26, 36, 19,
       35,  6, 33, 38, 15, 20, 10, 28, 31, 20, 22, 26, 12, 36, 34, 17, 37,
       21, 27,  7, 22, 35, 21, 15, 10, 36, 32, 20,  7,  9, 21, 36, 22])

In [13]:
ranges = [5,12,18,35,50]
age_bins = pd.cut(ages, ranges)
age_bins.describe()

counts  freqs
categories               
(5, 12]          9   0.18
(12, 18]         4   0.08
(18, 35]        26   0.52
(35, 50]        11   0.22

#### pd.qcut 같은 갯수로 구간 나누기

In [14]:
same_cnt_bin = pd.qcut(normal,5)
same_cnt_bin.describe()

counts  freqs
categories                                  
(-3.6599999999999997, -0.833]    2000    0.2
(-0.833, -0.253]                 2000    0.2
(-0.253, 0.254]                  2000    0.2
(0.254, 0.832]                   2000    0.2
(0.832, 3.738]                   2000    0.2

In [ ]:
df_a['cat'] = pd.qcut(df_a.age, q = 3, labels = ['g1','g2','g3'])
df_a.groupby('cat').median().age

## T1-22. Time-Series
주어진 데이터(basic2.csv)에서 주 단위 Sales의 합계를 구하고, 가장 큰 값을 가진 주와 작은 값을 가진 주의 차이를 구하시오(절대값)

#### 단위
- 주 단위: W
- 2주 단위: 2W
- 월 단위: M


In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')

df.resample('W').sum()
df.resample('M').sum()

## T1-23. 중복 데이터 제거

f1의 결측치를 채운 후 age 컬럼의 중복 제거 전과 후의 'f1' 중앙값 차이를 구하시오
- 결측치는 f1의 데이터 중 내림차순 정렬 후 10번째 값으로 채움
- 중복 데이터 발생시 뒤에 나오는 데이터를 삭제함
- 최종 결과값은 절대값으로 출력

In [ ]:
df.f1.sort_values(ascending = False).iloc[9]

# 중복
df.age.duplicated().sum()
df.drop_duplicates('age').f1.median()

## T1-24. Time-Series(Lagged Feature)

주어진 데이터(basic2.csv)에서 "pv"컬럼으로 1일 시차(lag)가 있는 새로운 컬럼을 만들고(예: 1월 2일에는 1월 1일 pv데이터를 넣고, 1월 3일에는 1월 2일 pv데이터를 넣음),

새로운 컬럼의 1월 1일은 다음날(1월 2일)데이터로 결측치를 채운 다음, 

Events가 1이면서 Sales가 1000000이하인 조건에 맞는 새로운 컬럼 합을 구하시오

In [ ]:
#1일 차이가 나는 시차 특성 만들기
df['previous_PV'] = df['PV'].shift(1)

# 바로 뒤의 값으로 채움
df.previous_PV.fillna(method = 'bfill')

## T1-25. str-slicing
basic1 데이터에서 f4가 E로 시작하면서 부산에 살고 20대인 사람은 몇 명일까

In [ ]:
### OK
df.f4.str.startswith('E')

## T1-26. str-contains
menu컬럼에 "라떼" 키워드가 있는 데이터의 수는?

In [ ]:
### OK
df.menu.str.contains('라떼').sum()

## T1-27. str-contains-replace
바닐라라떼 5점, 카페라떼 3점, 아메리카노 2점, 나머지 0점이다 총 메뉴의 점수를 더한 값은?

In [ ]:
df.menu = df.menu.str.replace(' ','')
m = {'바닐라라떼': 5, '카페라떼': 3, '아메리카노': 2}
df.menu.map(m).fillna(0).sum()

## T1-28. value-counts-index
시간(hour)이 13시 이전(13시 포함하지 않음) 데이터 중 가장 많은 결제가 이루어진 날짜(date)는? (date 컬럼과 동일한 양식으로 출력)

## T1-29. datetime-format

In [ ]:
pd.to_datetime(df.date, format = '%Y%m%d')

## T1-30. datetime-percent
12월 25일 결제 금액(price)은 12월 총 결제금액의 몇 %인가? (정수로 출력)

In [ ]:
int(df[df.date == '2022-12-25'].price.sum() / df[ df.date.dt.month == 12 ].price.sum() * 100)

## T1-31 melt
수학, 영어, 국어 점수 중 사람과 과목에 상관없이 가장 상위 점수 5개를 모두 더하고 출력하

In [ ]:
df.drop('Name', axis = 1).unstack().sort_values(ascending = False)[:5].sum()

#### 데이터 재구조화(reshape)

#### 1) pivot(), pd.pivot_table()
- data.pivot(index, columns, values)
- pd.pivot_table(data, index, columns, values, aggfunc, margins)
<br>

- .pivot()은 종종 에러가 남. 중복값이 있을 경우 valueError
    - index가 2개 이상인 경우
    - columns이 2개 이상인 경우
<br>
- pd.pivot_table() 잘 숙지
    - aggfunc을 사용할 수 있으므로 index 중복값이 있어도 괜찮음
    - margins = True 옵션 설정 시, 행과 열 기준으로 합계를 제시해줌

In [18]:
data = pd.DataFrame({'cust_id': ['c1', 'c1', 'c1', 'c2', 'c2', 'c2', 'c3', 'c3', 'c3'],
                  'prod_cd': ['p1', 'p2', 'p3', 'p1', 'p2', 'p3', 'p1', 'p2', 'p3'],
                  'grade' : ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B'],
                  'pch_amt': [30, 10, 0, 40, 15, 30, 0, 0, 10]})
data.head(3)

cust_id prod_cd grade  pch_amt
0      c1      p1     A       30
1      c1      p2     A       10
2      c1      p3     A        0

In [19]:
data_pv = data.pivot(index = 'cust_id', columns = 'prod_cd', values = 'pch_amt')
data_pv.head(3)

prod_cd  p1  p2  p3
cust_id            
c1       30  10   0
c2       40  15  30
c3        0   0  10

In [20]:
pd.pivot_table(data, index = 'cust_id', columns = 'prod_cd', values = 'pch_amt')

prod_cd  p1  p2  p3
cust_id            
c1       30  10   0
c2       40  15  30
c3        0   0  10

In [31]:
### pivot() with index which contains duplicate entries: ValueError
data.pivot(index = 'grade', columns = 'prod_cd', values = 'pch_amt')

ValueError: Index contains duplicate entries, cannot reshape

In [30]:
pd.pivot_table(data, index = 'grade', columns = 'prod_cd', values = 'pch_amt', aggfunc = np.sum) 
# default는 mean

prod_cd  p1  p2  p3
grade              
A        70  25  30
B         0   0  10

In [32]:
pd.pivot_table(data, index = 'grade', columns = 'prod_cd', values = 'pch_amt', aggfunc = np.sum, margins = True) 

prod_cd  p1  p2  p3  All
grade                   
A        70  25  30  125
B         0   0  10   10
All      70  25  40  135

#### 2) stack(), unstack()
- stack(long) 쌓다, 위에서 아래로 길개 쌓기
- unstack(wide) 쌓은 것을 옆으로 늘어놓기 

In [35]:
data = pd.DataFrame(data=np.arange(16).reshape(4, 4),
                 index=pd.MultiIndex.from_tuples([('cust_1', '2015'), ('cust_1', '2016'),('cust_2', '2015'), ('cust_2', '2016')]),
                 columns=['prd_1', 'prd_2', 'prd_3', 'prd_4'],
                 dtype='int')
data

prd_1  prd_2  prd_3  prd_4
cust_1 2015      0      1      2      3
       2016      4      5      6      7
cust_2 2015      8      9     10     11
       2016     12     13     14     15

In [36]:
data.stack()    # returns series

cust_1  2015  prd_1     0
              prd_2     1
              prd_3     2
              prd_4     3
        2016  prd_1     4
              prd_2     5
              prd_3     6
              prd_4     7
cust_2  2015  prd_1     8
              prd_2     9
              prd_3    10
              prd_4    11
        2016  prd_1    12
              prd_2    13
              prd_3    14
              prd_4    15
dtype: int32

In [37]:
data.stack().index

MultiIndex([('cust_1', '2015', 'prd_1'),
            ('cust_1', '2015', 'prd_2'),
            ('cust_1', '2015', 'prd_3'),
            ('cust_1', '2015', 'prd_4'),
            ('cust_1', '2016', 'prd_1'),
            ('cust_1', '2016', 'prd_2'),
            ('cust_1', '2016', 'prd_3'),
            ('cust_1', '2016', 'prd_4'),
            ('cust_2', '2015', 'prd_1'),
            ('cust_2', '2015', 'prd_2'),
            ('cust_2', '2015', 'prd_3'),
            ('cust_2', '2015', 'prd_4'),
            ('cust_2', '2016', 'prd_1'),
            ('cust_2', '2016', 'prd_2'),
            ('cust_2', '2016', 'prd_3'),
            ('cust_2', '2016', 'prd_4')],
           )

In [39]:
data.unstack(level = 1)  # default

prd_1      prd_2      prd_3      prd_4     
        2015 2016  2015 2016  2015 2016  2015 2016
cust_1     0    4     1    5     2    6     3    7
cust_2     8   12     9   13    10   14    11   15

In [40]:
data.unstack(level = 0)

prd_1         prd_2         prd_3         prd_4       
     cust_1 cust_2 cust_1 cust_2 cust_1 cust_2 cust_1 cust_2
2015      0      8      1      9      2     10      3     11
2016      4     12      5     13      6     14      7     15

#### 3) melt()
- ID변수를 기준으로, 원래 데이터셋에 있던 여러개의 컬럼을 'variable' 컬럼 위에 아래로 길게 쌓아놓고, 'value' 컬럼에 ID와 variable에 해당하는 값을 넣어줌


In [4]:
data = pd.DataFrame({'cust_ID' : ['C_001', 'C_001', 'C_002', 'C_002'],
'prd_CD' : ['P_001', 'P_002', 'P_001', 'P_002'],
'pch_cnt' : [1, 2, 3, 4],
'pch_amt' : [100, 200, 300, 400]})
data

cust_ID prd_CD  pch_cnt  pch_amt
0   C_001  P_001        1      100
1   C_001  P_002        2      200
2   C_002  P_001        3      300
3   C_002  P_002        4      400

In [5]:
pd.melt(data)

variable  value
0   cust_ID  C_001
1   cust_ID  C_001
2   cust_ID  C_002
3   cust_ID  C_002
4    prd_CD  P_001
5    prd_CD  P_002
6    prd_CD  P_001
7    prd_CD  P_002
8   pch_cnt      1
9   pch_cnt      2
10  pch_cnt      3
11  pch_cnt      4
12  pch_amt    100
13  pch_amt    200
14  pch_amt    300
15  pch_amt    400

In [6]:
# id_variable
pd.melt(data, id_vars = ['cust_ID','prd_CD'])

cust_ID prd_CD variable  value
0   C_001  P_001  pch_cnt      1
1   C_001  P_002  pch_cnt      2
2   C_002  P_001  pch_cnt      3
3   C_002  P_002  pch_cnt      4
4   C_001  P_001  pch_amt    100
5   C_001  P_002  pch_amt    200
6   C_002  P_001  pch_amt    300
7   C_002  P_002  pch_amt    400

In [12]:
# variable, value 이름 부여
data_melt = pd.melt(data, id_vars = ['cust_ID','prd_CD'], var_name = 'pch_CD', value_name = 'pch_value')
data_melt

cust_ID prd_CD   pch_CD  pch_value
0   C_001  P_001  pch_cnt          1
1   C_001  P_002  pch_cnt          2
2   C_002  P_001  pch_cnt          3
3   C_002  P_002  pch_cnt          4
4   C_001  P_001  pch_amt        100
5   C_001  P_002  pch_amt        200
6   C_002  P_001  pch_amt        300
7   C_002  P_002  pch_amt        400

In [13]:
# pd.melt() vs pd.pivot_table()
data_pivot = pd.pivot_table(data_melt, index = ['cust_ID','prd_CD'], columns = 'pch_CD', values = 'pch_value', aggfunc = np.mean)
data_pivot

pch_CD          pch_amt  pch_cnt
cust_ID prd_CD                  
C_001   P_001       100        1
        P_002       200        2
C_002   P_001       300        3
        P_002       400        4

In [15]:
data_melt.index, data_pivot.index

(RangeIndex(start=0, stop=8, step=1),
 MultiIndex([('C_001', 'P_001'),
             ('C_001', 'P_002'),
             ('C_002', 'P_001'),
             ('C_002', 'P_002')],
            names=['cust_ID', 'prd_CD']))

#### 4) wide_to_long()

#### 5) pd.crosstab() 

## T1-31 melt
수학, 영어 점수 중 사람과 과목에 상관없이 90점 이상인 점수의 평균을 정수로 구하시오 (소수점 버림)

In [ ]:
int(df.drop(['Name','국어'], axis = 1).unstack()[df.drop('Name', axis = 1).unstack() >= 90].mean())

In [ ]:
pd.melt(df, id_vars = ['Name'], value_vars = ['수학','영어'], var_name = '과목',value_name = '점수')

## T1-92 sigmoid
basic1 데이터에서 f2 값에 시그모이드 함수(그림 내 수식)를 적용하고, f4가 ISFJ인 (변경된)f2의 합을 구하시오! (소수점 둘째자리까지 출력, 반올림)

In [ ]:
def sig(x):
    return 1 / (1 + np.exp(-x))
df.f2 = df.f2.apply(sig)

## T2-relu
basic1 데이터에서 age 값에 ReLU 함수를 적용하고, city가 부산인 (변경된)age의 평균을 구하시오! (소수점 둘째자리까지 출력, 절사)

In [ ]:
def relu(x):
    if x>0:
        return x
    else:
        return 0

def relu(x):
    return np.maximum(0, x)